services:
  - type: web
    name: OnlineBazar
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn OnlineBazar.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgres://youruser:yourpassword@yourhost:yourport/yourdbname
      - key: SECRET_KEY
        value: your-very-secret-django-key
      - key: DEBUG
        value: "False"