# Generated by Django 4.2 on 2025-07-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='username',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
        ),
    ]
