# Generated by Django 4.2 on 2025-07-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_chatsession_username_chatsession_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.buyer'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.seller'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='mainApp_cha_session_30f28b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='mainApp_cha_session_14f535_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['buyer'], name='mainApp_cha_buyer_i_6ab2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['seller'], name='mainApp_cha_seller__09df5d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_at'], name='mainApp_cha_created_f33d38_idx'),
        ),
    ]
