# Generated by Django 4.2 on 2025-07-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_chatsession_buyer_alter_chatsession_seller_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='mainApp_cha_session_30f28b_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='mainApp_cha_session_14f535_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='mainApp_cha_buyer_i_6ab2a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='mainApp_cha_seller__09df5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='mainApp_cha_created_f33d38_idx',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='seller',
        ),
    ]
