# Generated by Django 4.2 on 2026-04-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_remove_chatmessage_mainapp_cha_session_30f28b_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutproducts",
            name="size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
