# Generated by Django 4.2 on 2026-04-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0010_review_image_review_likes_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutproducts",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.seller",
            ),
        ),
    ]
