# Generated by Django 5.2.13 on 2026-04-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0011_checkoutproducts_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainApp.buyer",
            ),
        ),
    ]
