# Generated by Django 5.2.13 on 2026-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0012_chatsession_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="guarantee",
            field=models.CharField(
                blank=True, default="7 Days Replacement", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.CharField(
                blank=True, default="6 Months Warranty", max_length=100, null=True
            ),
        ),
    ]
