# Generated by Django 5.2.13 on 2026-04-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0013_product_guarantee_product_warranty"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(default="contact@citymobile.in", max_length=100),
                ),
                ("phone", models.CharField(default="+91 6205102076", max_length=15)),
                (
                    "address",
                    models.TextField(default="123 Shopping Street, New Delhi, India"),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True, default="https://facebook.com", null=True
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, default="https://instagram.com", null=True
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True, default="https://twitter.com", null=True
                    ),
                ),
                (
                    "map_link",
                    models.TextField(
                        blank=True, help_text="Google Maps Embed Link", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Store Information",
            },
        ),
    ]
